### ISSUE TITLE
Documentation in firmware has incorrect i2c command values

### ISSUE THREAD

**Issue by querry43** [sparkfunX/Qwiic_MP3_Trigger#3]
The comment header for Qwiic_MP3_Controller.ino lists the command values incorrectly.  As one example, it has:

> 0x0A : Get firmware version : 2 bytes, upper ver and lower ver

when the actual value is:

> #define COMMAND_GET_VERSION 0x0C

**Comment by nseidle** [comment]
Good catch! Thanks for reporting the issue. I think I've updated the main firmware ino with the correct commands. Let me know if there's anything else that has issues.
